// ─────────────────────────────────────────────────────────────────────────────
// Bundled shop-chrome dictionary (EN + HR).
//
// The storefront's shop UI (grid, product page, cart, checkout, account, orders,
// facets, reviews …) is generic across every commerce project, so its chrome
// strings ship here as a built-in default instead of forcing each project to seed
// them. `useStrings().t(key)` resolves in this order:
//   1. project strings store (admin-editable, per-project override)
//   2. this bundled dict, in the active locale
//   3. this bundled dict, in the fallback locale ("en")
//   4. the literal key (the "fill me in" signal for genuinely missing copy)
//
// Keys are namespaced `shop.*`. Add both EN and HR for every new key.
// ─────────────────────────────────────────────────────────────────────────────

export const SHOP_FALLBACK_LOCALE = "en";

type Dict = Record<string, string>;

const en: Dict = {
  // Header / nav
  "shop.nav.shop": "Shop",
  "shop.nav.cart": "Cart",
  "shop.nav.account": "Account",
  "shop.nav.signIn": "Sign in",
  "shop.nav.orders": "Orders",
  "shop.nav.wishlist": "Wishlist",

  // Generic
  "shop.loading": "Loading…",
  "shop.save": "Save",
  "shop.cancel": "Cancel",
  "shop.edit": "Edit",
  "shop.delete": "Delete",
  "shop.remove": "Remove",
  "shop.close": "Close",
  "shop.back": "Back",
  "shop.continue": "Continue",
  "shop.retry": "Try again",
  "shop.optional": "optional",
  "shop.somethingWrong": "Something went wrong. Please try again.",

  // Catalog / grid
  "shop.catalog.title": "Shop",
  "shop.catalog.searchPlaceholder": "Search products…",
  "shop.catalog.clearSearch": "Clear search",
  "shop.catalog.sortLabel": "Sort products",
  "shop.catalog.noImage": "No image",
  "shop.catalog.noMatches": "No products match your filters.",
  "shop.catalog.productCountOne": "product",
  "shop.catalog.productCountOther": "products",
  "shop.sort.newest": "Newest",
  "shop.sort.priceAsc": "Price: low → high",
  "shop.sort.priceDesc": "Price: high → low",
  "shop.sort.nameAsc": "Name: A → Z",
  "shop.sort.nameDesc": "Name: Z → A",

  // Badges / stock
  "shop.badge.inquiryOnly": "Inquiry only",
  "shop.badge.sale": "Sale",
  "shop.badge.inStock": "In stock",
  "shop.badge.backorder": "Backorder",
  "shop.badge.backorderAvailable": "Available on backorder",
  "shop.badge.outOfStock": "Out of stock",
  "shop.badge.verifiedPurchase": "Verified purchase",
  "shop.priceOnRequest": "Price on request",

  // Facets
  "shop.facets.title": "Filters",
  "shop.facets.clearAll": "Clear all",
  "shop.facets.category": "Category",
  "shop.facets.allCategories": "All categories",
  "shop.facets.type": "Type",
  "shop.facets.allTypes": "All types",
  "shop.facets.price": "Price (€)",
  "shop.facets.min": "Min",
  "shop.facets.max": "Max",
  "shop.facets.inStockOnly": "In stock only",
  "shop.facets.categoryFallback": "Category",
  "shop.type.physical": "Physical",
  "shop.type.digital": "Digital",
  "shop.type.service": "Service",

  // Product page
  "shop.product.quantity": "Quantity",
  "shop.product.addToCart": "Add to cart",
  "shop.product.addToInquiry": "Add to inquiry",
  "shop.product.selectOptions": "Select all options to see price + availability.",
  "shop.product.priceOnRequest": "Price on request",
  "shop.product.inStockCount": "In stock",
  "shop.product.sku": "SKU",
  "shop.product.lowestPrice": "Lowest price in the last 30 days",
  "shop.product.notFound": "Product not found.",

  // Wishlist button
  "shop.wishlist.add": "Add to wishlist",
  "shop.wishlist.remove": "Remove from wishlist",

  // Back-in-stock
  "shop.backInStock.notifyMe": "Notify me when back in stock",
  "shop.backInStock.emailPlaceholder": "Your email",
  "shop.backInStock.subscribe": "Notify me",
  "shop.backInStock.done": "We'll email you when this is back in stock.",
  "shop.backInStock.alreadyInStock": "This item is back in stock.",
  "shop.backInStock.error": "Could not subscribe. Please try again.",

  // Reviews
  "shop.reviews.title": "Reviews",
  "shop.reviews.none": "No reviews yet.",
  "shop.reviews.anonymous": "Anonymous",
  "shop.reviews.awaitingApproval": "Your review is awaiting approval.",
  "shop.reviews.write": "Write a review",
  "shop.reviews.titlePlaceholder": "Title (optional)",
  "shop.reviews.bodyPlaceholder": "Share your experience (optional)",
  "shop.reviews.submit": "Submit review",
  "shop.reviews.pickRating": "Pick a star rating first.",
  "shop.reviews.thanks": "Thanks! Your review is awaiting approval.",
  "shop.reviews.signInToReview": "to write a review.",
  "shop.reviews.verifyToReview": "Verify your email to write a review.",
  "shop.reviews.buyersOnly": "Only customers who bought this product can write a review.",
  "shop.reviews.exists": "You already reviewed this product.",
  "shop.reviews.submitError": "Could not submit the review. Please try again.",

  // Wishlist button
  "shop.wishlist.save": "Save",
  "shop.wishlist.saved": "Saved",

  // Header extras
  "shop.nav.skipToContent": "Skip to content",
  "shop.nav.cookieSettings": "Cookie settings",

  // Catalog extras
  "shop.catalog.browse": "Browse:",
  "shop.category.subcategories": "Subcategories:",

  // Back-in-stock extras
  "shop.backInStock.title": "Get notified when it's back",
  "shop.backInStock.emailExample": "you@example.com",
  "shop.backInStock.confirmed": "\u2713 We'll let you know when it's back.",
  "shop.backInStock.alreadyOnList": "You're already on the list \u2014 we'll email you when it's back.",
  "shop.backInStock.willEmail": "We'll email you when it's back in stock.",
  "shop.backInStock.subscribeError": "Couldn't subscribe. Check the email address and try again.",

  // Product extras
  "shop.product.backToShop": "\u2190 Back to shop",
  "shop.product.addedToCart": "cart",
  "shop.product.addedToInquiry": "inquiry",

  // Cookie banner
  "shop.cookie.text": "We use analytics cookies to understand how the shop is used. They are set only if you accept \u2014 declining keeps the shop fully functional.",
  "shop.cookie.decline": "Decline",
  "shop.cookie.accept": "Accept analytics",
  "shop.cookie.region": "Cookie consent",

  // Cart
  "shop.cart.title": "Your cart",
  "shop.cart.empty": "Your cart is empty.",
  "shop.cart.continueShopping": "\u2190 Continue shopping",
  "shop.cart.clear": "Clear cart",
  "shop.cart.summary": "Summary",
  "shop.cart.businessPricing": "Business pricing",
  "shop.cart.remove": "Remove",
  "shop.cart.removeCoupon": "Remove coupon",
  "shop.cart.decrease": "Decrease",
  "shop.cart.increase": "Increase",
  "shop.cart.max": "max",
  "shop.cart.onRequest": "On request",
  "shop.cart.inquiryPriceOnRequest": "Inquiry \u2014 price on request",
  "shop.cart.mixedInquiryNote": "Your cart contains inquiry-only items, so the whole order becomes a quote request \u2014 no payment or delivery is calculated here. To buy the other items now, remove the inquiry-only items from your cart.",
  "shop.cart.inquiryNote": "These items are inquiry-only \u2014 we'll prepare a quote and follow up by email. No payment or delivery is calculated here.",
  "shop.cart.sendInquiry": "Send an inquiry",
  "shop.cart.coupon": "Coupon",
  "shop.cart.freeShipping": "Free shipping",
  "shop.cart.couponsAdditive": "Each coupon is applied to the original subtotal (discounts add up).",
  "shop.cart.addAnotherCoupon": "Add another coupon",
  "shop.cart.couponCode": "Coupon code",
  "shop.cart.couponSolo": "This coupon can't be combined with others — remove it to use a different code.",
  "shop.cart.couponApplied": "Coupon applied.",
  "shop.cart.couponRemoved": "Coupon removed — it's no longer valid for this cart.",
  "shop.cart.err.not_purchasable": "This product isn't available for purchase right now.",
  "shop.cart.err.out_of_stock": "Sorry — that item is out of stock.",
  "shop.cart.err.coupon_not_found": "That coupon code wasn't found.",
  "shop.cart.err.coupon_not_applicable": "That coupon can't be applied to your cart.",
  "shop.cart.err.below_min_spend": "Your cart is below this coupon's minimum spend",
  "shop.cart.err.coupon_expired": "That coupon has expired.",
  "shop.cart.err.coupon_not_started": "That coupon isn't active yet.",
  "shop.cart.err.coupon_inactive": "That coupon is no longer active.",
  "shop.cart.err.usage_exhausted": "That coupon has reached its usage limit.",
  "shop.cart.err.coupon_already_applied": "That coupon is already applied.",
  "shop.cart.err.not_stackable": "That coupon can't be combined with another — use it on its own.",
  "shop.cart.err.pickup_point_required": "Please pick a pickup point for this method.",
  "shop.cart.err.shipping_method_not_found": "That shipping method is no longer available.",
  "shop.cart.err.default": "Something went wrong with your cart. Please try again.",
  "shop.cart.apply": "Apply",
  "shop.cart.shipping": "Shipping",
  "shop.cart.shipTo": "Ship to",
  "shop.cart.pickupPoint": "Pickup point",
  "shop.cart.pickupSuffix": " (pickup point)",
  "shop.cart.free": "Free",
  "shop.cart.use": "Use",
  "shop.cart.noShippingMethods": "No shipping methods available for this destination.",
  "shop.cart.pickup": "Pickup",
  "shop.cart.subtotal": "Subtotal",
  "shop.cart.discount": "Discount",
  "shop.cart.cashOnDelivery": "Cash on delivery",
  "shop.cart.net": "Net",
  "shop.cart.vat": "VAT",
  "shop.cart.taxBase": "base",
  "shop.cart.total": "Total",
  "shop.cart.vatExempt": "Prices are VAT-exempt \u2014 the shop is not in the VAT system.",
  "shop.cart.vatIncluded": "VAT included",
  "shop.cart.vatReverse": "VAT reverse-charged \u2014 your business self-accounts for VAT",
  "shop.cart.vatExport": "Zero-rated export \u2014 no EU VAT is charged on delivery outside the EU",
  "shop.cart.noVat": "No VAT applies to these items.",
  "shop.country.eu": "EU",
  "shop.country.intl": "intl.",
  "shop.cart.checkout": "Proceed to checkout",

  // Order/payment/fulfillment/quote status labels (raw enum -> human)
  "shop.status.open": "Open",
  "shop.status.completed": "Completed",
  "shop.status.cancelled": "Cancelled",
  "shop.status.pending": "Pending",
  "shop.status.awaiting_payment": "Awaiting payment",
  "shop.status.authorized": "Authorized",
  "shop.status.paid": "Paid",
  "shop.status.partially_refunded": "Partially refunded",
  "shop.status.refunded": "Refunded",
  "shop.status.voided": "Voided",
  "shop.status.draft": "Draft",
  "shop.status.unfulfilled": "Unfulfilled",
  "shop.status.preparing": "Preparing",
  "shop.status.partially_shipped": "Partially shipped",
  "shop.status.shipped": "Shipped",
  "shop.status.delivered": "Delivered",
  "shop.status.returned": "Returned",
  "shop.status.sent": "Sent",
  "shop.status.accepted": "Accepted",
  "shop.status.declined": "Declined",
  "shop.status.expired": "Expired",

  // Orders history
  "shop.orders.title": "My orders",
  "shop.orders.signInPrompt": "to view your order history.",
  "shop.orders.pleaseSignIn": "Please",
  "shop.orders.signIn": "sign in",
  "shop.orders.verifyTitle": "Verify your email",
  "shop.orders.verifyBody": "Your order history is an account feature \u2014 please verify your email first. Verifying also links any earlier orders you placed as a guest with this email.",
  "shop.orders.goToAccount": "Go to your account",
  "shop.orders.loadFailedTitle": "Couldn't load your orders",
  "shop.orders.loadFailedBody": "Something went wrong loading your order history.",
  "shop.orders.tryAgain": "Try again",
  "shop.orders.emptyBody": "You haven't placed any orders yet.",
  "shop.orders.startShopping": "Start shopping",
  "shop.orders.quote": "Quote",
  "shop.orders.order": "Order",
  "shop.orders.itemOne": "item",
  "shop.orders.itemOther": "items",
  "shop.orders.backToAccount": "\u2190 Back to account",

  // Wishlist page
  "shop.wishlistPage.title": "Wishlist",
  "shop.wishlistPage.backToAccount": "\u2190 Back to account",
  "shop.wishlistPage.continueShopping": "\u2190 Continue shopping",
  "shop.wishlistPage.guestNote": "Your wishlist is saved on this device.",
  "shop.wishlistPage.guestNoteSuffix": "(and verify your email) to keep it across devices.",
  "shop.wishlistPage.empty": "Your wishlist is empty. Tap the heart on any product to save it here.",
  "shop.wishlistPage.browse": "Browse the shop",
  "shop.wishlistPage.savedOne": "saved item",
  "shop.wishlistPage.savedOther": "saved items",

  // Payment (Stripe)
  "shop.payment.payNow": "Pay now",
  "shop.payment.failed": "Payment failed. Please try again.",
  "shop.payment.testMode": "Test mode \u2014 use card 4242 4242 4242 4242, any future expiry & CVC.",

  // Auth: forgot / reset / verify
  "shop.auth.resetTitle": "Reset your password",
  "shop.auth.checkInbox": "Check your inbox",
  "shop.auth.resetSentPrefix": "If an account exists for",
  "shop.auth.resetSentSuffix": "we've sent a password-reset link. The link expires in 1 hour.",
  "shop.auth.backToSignIn": "Back to sign in",
  "shop.auth.forgotIntro": "Enter your email and we'll send you a link to choose a new password.",
  "shop.auth.email": "Email",
  "shop.auth.sendResetLink": "Send reset link",
  "shop.auth.chooseNewPassword": "Choose a new password",
  "shop.auth.checkingLink": "Checking your link…",
  "shop.auth.linkInvalidTitle": "Link invalid or expired",
  "shop.auth.resetLinkInvalid": "This password-reset link is invalid or has expired. Request a new one.",
  "shop.auth.requestNewLink": "Request a new link",
  "shop.auth.settingPasswordFor": "Setting a new password for",
  "shop.auth.newPassword": "New password",
  "shop.auth.atLeast8": "At least 8 characters",
  "shop.auth.confirmPassword": "Confirm password",
  "shop.auth.passwordsDontMatch": "Passwords don't match",
  "shop.auth.setNewPassword": "Set new password",
  "shop.auth.verifyTitle": "Email verification",
  "shop.auth.verifying": "Verifying your email…",
  "shop.auth.verifiedTitle": "Email verified",
  "shop.auth.verifiedBody": "Thanks! Your email address is confirmed and your account features are unlocked.",
  "shop.auth.goToAccount": "Go to my account",
  "shop.auth.verifyFailedTitle": "Couldn't verify",
  "shop.auth.verifyFailedBody": "This verification link is invalid or has expired. Sign in and request a fresh link from your account page.",

  // Account page
  "shop.account.myAccount": "My account",
  "shop.account.title": "Account",
  "shop.account.typePersonal": "personal",
  "shop.account.typeBusiness": "business",
  "shop.account.emailVerified": "Email verified:",
  "shop.account.verified": "verified",
  "shop.account.notVerified": "not verified",
  "shop.account.businessPricing": "Business pricing:",
  "shop.account.b2bActive": "active",
  "shop.account.b2bNotApproved": "not approved",
  "shop.account.b2bPending": "pending approval",
  "shop.account.b2bPendingTitle": "Business account pending approval",
  "shop.account.b2bPendingBody": "Your business account is awaiting approval. You can shop now at standard prices \u2014 once approved, your assigned price list applies automatically across the store.",
  "shop.account.verifyTitle": "Verify your email",
  "shop.account.verifyBodyPrefix": "We sent a verification link to",
  "shop.account.verifyBodySuffix": ". Verifying unlocks account features like changing your password \u2014 but you can keep shopping and checking out in the meantime.",
  "shop.account.resendVerification": "Resend verification email",
  "shop.account.changePassword": "Change password",
  "shop.account.currentPassword": "Current password",
  "shop.account.newPassword": "New password",
  "shop.account.confirmNewPassword": "Confirm new password",
  "shop.account.passwordsDontMatch": "Passwords don't match",
  "shop.account.updatePassword": "Update password",
  "shop.account.verifyToChangePassword": "Verify your email to change your password.",
  "shop.account.myOrders": "My orders",
  "shop.account.addressBook": "Address book",
  "shop.account.wishlist": "Wishlist",
  "shop.account.viewCart": "View cart",
  "shop.account.signOut": "Sign out",
  "shop.account.cartMovePrefix": "You have",
  "shop.account.cartMoveOne": "item in your cart \u2014 sign in or create an account and it will move with you.",
  "shop.account.cartMoveOther": "items in your cart \u2014 sign in or create an account and it will move with you.",
  "shop.account.signIn": "Sign in",
  "shop.account.createAccount": "Create account",
  "shop.account.email": "Email",
  "shop.account.password": "Password",
  "shop.account.forgotPassword": "Forgot your password?",
  "shop.account.personal": "Personal",
  "shop.account.businessB2B": "Business (B2B)",
  "shop.account.company": "Company",
  "shop.account.oib": "OIB",
  "shop.account.oib11": "11 digits",
  "shop.account.vatId": "VAT ID",
  "shop.account.vatIdExample": "e.g. HR12345678901",
  "shop.account.b2bHint": "Provide an OIB (11 digits) or an EU VAT ID. Business accounts are reviewed before B2B pricing applies \u2014 you can shop at standard prices in the meantime.",
  "shop.account.firstName": "First name",
  "shop.account.lastName": "Last name",
  "shop.account.confirmPassword": "Confirm password",
  "shop.account.atLeast8": "At least 8 characters",
  "shop.account.businessMustUseForm": "Business accounts must be created with the form above.",
  "shop.account.or": "or",
  "shop.account.guestCheckout": "Guest checkout is always available \u2014 an account is optional.",
  "shop.account.continueShopping": "Continue shopping",
  "shop.account.required": "Required.",
  "shop.account.invalidEmail": "Enter a valid email address.",
  "shop.account.min8": "At least 8 characters.",
  "shop.account.provideTaxId": "Provide an OIB or a VAT ID.",
  "shop.account.invalidOib": "Invalid OIB \u2014 11 digits with a valid checksum.",
  "shop.account.invalidVatId": "Enter a valid VAT ID.",
  "shop.oauth.google": "Continue with Google",
  "shop.oauth.apple": "Continue with Apple",
  "shop.oauth.stub": "Dev sign-in (stub)",
  "shop.oauth.err.oauth_failed": "Sign-in didn't complete. Please try again.",
  "shop.oauth.err.oauth_account_exists": "An account with this email already exists. Sign in with your password (or reset it), then you can connect this provider.",
  "shop.oauth.err.oauth_email_unverified": "The provider didn't share a verified email, so we couldn't sign you in.",
  "shop.oauth.err.account_disabled": "This account has been disabled.",
  "shop.oauth.linked": "Signed in \u2014 this provider is now linked to your account.",
  "shop.oauth.signedIn": "Signed in.",

  // Address book
  "shop.addr.title": "Address book",
  "shop.addr.signInPrompt": "to manage your saved addresses.",
  "shop.addr.verifyTitle": "Verify your email",
  "shop.addr.verifyBody": "Saving addresses is an account feature \u2014 please verify your email first. You can still check out as a guest by entering an address at checkout.",
  "shop.addr.goToAccount": "Go to your account",
  "shop.addr.add": "Add address",
  "shop.addr.empty": "You haven't saved any addresses yet. Add one and it'll prefill at checkout.",
  "shop.addr.defaultShipping": "Default shipping",
  "shop.addr.defaultBilling": "Default billing",
  "shop.addr.setDefaultShipping": "Set default shipping",
  "shop.addr.setDefaultBilling": "Set default billing",
  "shop.addr.edit": "Edit",
  "shop.addr.confirm": "Confirm",
  "shop.addr.cancel": "Cancel",
  "shop.addr.delete": "Delete",
  "shop.addr.backToAccount": "\u2190 Back to account",
  "shop.addr.editTitle": "Edit address",
  "shop.addr.addTitle": "Add address",
  "shop.addr.label": "Label (optional)",
  "shop.addr.labelPlaceholder": "Home, Work…",
  "shop.addr.fullName": "Full name",
  "shop.addr.address": "Address",
  "shop.addr.addressLine2": "Address line 2",
  "shop.addr.city": "City",
  "shop.addr.postalCode": "Postal code",
  "shop.addr.country": "Country (ISO-2)",
  "shop.addr.phone": "Phone",
  "shop.addr.defaultShippingCheckbox": "Default shipping address",
  "shop.addr.defaultBillingCheckbox": "Default billing address",
  "shop.addr.saveChanges": "Save changes",
  "shop.addr.updated": "Address updated.",
  "shop.addr.saved": "Address saved.",
  "shop.addr.verifyToSave": "Verify your email first to save addresses.",
  "shop.addr.saveError": "Couldn't save the address. Please check the fields and try again.",
  "shop.addr.defaultError": "Couldn't update the default address.",
  "shop.addr.removed": "Address removed.",
  "shop.addr.removeError": "Couldn't remove the address.",

  // Checkout
  "shop.checkout.title": "Checkout",
  "shop.checkout.sendInquiry": "Send an inquiry",
  "shop.checkout.empty": "Your cart is empty.",
  "shop.checkout.continueShopping": "\u2190 Continue shopping",
  "shop.checkout.mixedQuotePrefix": "Your cart contains inquiry-only items, so the whole order is a",
  "shop.checkout.quoteRequest": "quote request",
  "shop.checkout.mixedQuoteSuffix": "\u2014 no payment or delivery is calculated. To pay for the other items now, go back to your cart and remove the inquiry-only items.",
  "shop.checkout.inquiryPrefix": "These items are inquiry-only, so this is a",
  "shop.checkout.inquirySuffix": ". No payment is taken now \u2014 we'll prepare a quote and follow up by email.",
  "shop.checkout.useSavedAddress": "Use a saved address",
  "shop.checkout.enterNewAddress": "Enter a new address",
  "shop.checkout.contact": "Contact",
  "shop.checkout.email": "Email",
  "shop.checkout.shippingAddress": "Shipping address",
  "shop.checkout.billingAddress": "Billing address",
  "shop.checkout.fullName": "Full name",
  "shop.checkout.address": "Address",
  "shop.checkout.addressLine2": "Address line 2",
  "shop.checkout.city": "City",
  "shop.checkout.postalCode": "Postal code",
  "shop.checkout.country": "Country",
  "shop.checkout.phone": "Phone",
  "shop.checkout.billingSame": "Billing address same as shipping",
  "shop.checkout.orderNote": "Order note",
  "shop.checkout.marketingOptIn": "Email me about offers and news",
  "shop.checkout.marketingHint": "Optional \u2014 you can unsubscribe any time.",
  "shop.checkout.backToCart": "\u2190 Back to cart",
  "shop.checkout.orderSummary": "Order summary",
  "shop.checkout.onRequest": "On request",
  "shop.checkout.noQuoteTotal": "No total is calculated for a quote \u2014 we'll send you a priced offer.",
  "shop.checkout.subtotal": "Subtotal",
  "shop.checkout.discount": "Discount",
  "shop.checkout.free": "Free",
  "shop.checkout.cashOnDelivery": "Cash on delivery",
  "shop.checkout.net": "Net",
  "shop.checkout.vat": "VAT",
  "shop.checkout.estimatedTotal": "Estimated total",
  "shop.checkout.total": "Total",
  "shop.checkout.vatExempt": "Prices are VAT-exempt \u2014 the shop is not in the VAT system.",
  "shop.checkout.vatShownFor": "VAT shown for",
  "shop.checkout.noVat": "No VAT applies to these items.",
  "shop.checkout.paymentMethod": "Payment method",
  "shop.checkout.noPayableMethod": "No payment method is available for this cart \u2014 your item requires cash on delivery, but the chosen shipping method doesn't support it. Pick a courier delivery method on the cart page.",
  "shop.checkout.chooseDelivery": "Choose a delivery method to continue.",
  "shop.checkout.selectOnCart": "Select one on the cart page",
  "shop.checkout.placeOrder": "Place order",
  "shop.checkout.fillToContinue": "Fill in your email + shipping address to continue.",
  "shop.checkout.enterValidEmail": "Enter a valid email address.",
  "shop.checkout.fullNameRequired": "Full name is required.",
  "shop.checkout.addressRequired": "Address is required.",
  "shop.checkout.cityRequired": "City is required.",
  "shop.checkout.postalRequired": "Postal code is required.",
  "shop.checkout.emailPlaceholder": "you@example.com",
  "shop.pay.pay_now": "Pay now (card)",
  "shop.pay.pay_now.help": "Pay securely by card on the next step.",
  "shop.pay.bank_transfer": "Bank transfer",
  "shop.pay.bank_transfer.help": "We'll email payment instructions; your order ships once payment arrives.",
  "shop.pay.cod": "Cash on delivery",
  "shop.pay.cod.help": "Pay in cash when your order is delivered (a surcharge applies).",
  "shop.checkout.err.cart_empty": "Your cart is empty.",
  "shop.checkout.err.insufficient_stock": "Sorry \u2014 one of your items just went out of stock.",
  "shop.checkout.err.coupon_exhausted": "Your coupon was just used up. Please remove it and try again.",
  "shop.checkout.err.payment_method_unavailable": "That payment method isn't available for this cart. Please pick another option.",
  "shop.checkout.err.default": "Checkout failed. Please try again.",

  // Status labels for returns
  "shop.status.requested": "Requested",
  "shop.status.approved": "Approved",
  "shop.status.rejected": "Rejected",

  // Order page
  "shop.order.notFound": "Order not found",
  "shop.order.notFoundBody": "We couldn't find that order.",
  "shop.order.continueShopping": "\u2190 Continue shopping",
  "shop.order.quoteReceivedPrefix": "Your",
  "shop.order.quoteRequest": "quote request",
  "shop.order.quoteReceivedMid": "has been received. We'll email a quote to",
  "shop.order.authorizedPrefix": "Your card is",
  "shop.order.authorized": "authorized",
  "shop.order.authorizedMid": "for order",
  "shop.order.authorizedSuffix": "\u2014 you won't be charged until it ships. A confirmation will go to",
  "shop.order.paidPrefix": "Payment received \u2014 thank you! Order",
  "shop.order.paidMid": "is confirmed. A receipt will go to",
  "shop.order.placedPrefix": "Thank you! Order",
  "shop.order.placedMid": "is placed and awaiting payment. A confirmation will go to",
  "shop.order.orderNo": "Order",
  "shop.order.invoicePdf": "Invoice (PDF)",
  "shop.order.yourDownloads": "Your downloads",
  "shop.order.linkExpired": "Link expired",
  "shop.order.download": "Download",
  "shop.order.linkValidUntil": "Link valid until",
  "shop.order.licenseKey": "License key",
  "shop.order.licenseKeys": "License keys",
  "shop.order.fulfill.preparing": "Your order is being prepared for shipment.",
  "shop.order.fulfill.partially_shipped": "Part of your order is on its way \u2014 the rest will follow.",
  "shop.order.fulfill.shipped": "Your order has shipped and is on its way.",
  "shop.order.fulfill.delivered": "Your order has been delivered. Enjoy!",
  "shop.order.fulfill.returned": "This order has been returned.",
  "shop.order.quoteReadyTitle": "Your quote is ready",
  "shop.order.quoteReviewPrefix": "Review the items and total below",
  "shop.order.quoteValidUntil": "valid until",
  "shop.order.quoteReviewSuffix": "Accept to confirm and proceed to payment, or decline if it no longer suits you.",
  "shop.order.acceptQuote": "Accept quote",
  "shop.order.decline": "Decline",
  "shop.order.acceptError.stock": "Some items are no longer in stock \u2014 we'll be in touch.",
  "shop.order.acceptError.generic": "Couldn't accept the quote. Please try again.",
  "shop.order.declineError": "Couldn't decline the quote. Please try again.",
  "shop.order.declinedNote": "You declined this quote.",
  "shop.order.payment": "Payment",
  "shop.order.bankTransferPrefix": "Pay by",
  "shop.order.bankTransfer": "bank transfer",
  "shop.order.bankTransferMid": "using the details on the proforma invoice below",
  "shop.order.by": "by",
  "shop.order.bankReserved": "Your order is reserved and ships once payment arrives.",
  "shop.order.downloadProforma": "Download proforma invoice (PDF)",
  "shop.order.codPrefix": "You'll",
  "shop.order.codPayInCash": "pay in cash on delivery",
  "shop.order.codSurchargePrefix": "(incl. a",
  "shop.order.codSurchargeSuffix": "COD surcharge)",
  "shop.order.codNoPaymentNow": ". No payment is needed now.",
  "shop.order.confirmingPayment": "Confirming your payment…",
  "shop.order.holdNotice": "We'll only place a hold on your card now \u2014 you're charged when your order ships.",
  "shop.order.authorizeIntro": "Authorize your card to confirm your order \u2014 you'll only be charged when it ships.",
  "shop.order.payIntro": "Pay securely by card to confirm your order.",
  "shop.order.authorizeCard": "Authorize card",
  "shop.order.payByCard": "Pay by card",
  "shop.order.payStartError": "Couldn't start the payment. Please try again.",
  "shop.order.followUpEmail": "We'll follow up by email with payment instructions.",
  "shop.order.items": "Items",
  "shop.order.shipped": "Shipped",
  "shop.order.shippedOf": "Shipped {n} of {total}",
  "shop.order.shipsSoon": "Ships soon",
  "shop.order.subtotal": "Subtotal",
  "shop.order.discount": "Discount",
  "shop.order.cashOnDelivery": "Cash on delivery",
  "shop.order.net": "Net",
  "shop.order.vat": "VAT",
  "shop.order.estimatedTotal": "Estimated total",
  "shop.order.total": "Total",
  "shop.order.noVatCharged": "No VAT was charged on this order.",
  "shop.order.shippingTo": "Shipping to",
  "shop.order.method": "Method",
  "shop.order.pickupPoint": "pickup point",
  "shop.order.billing": "Billing",
  "shop.order.returns": "Returns",
  "shop.order.returnsEmailPrefix": "To request a return, please email us at",
  "shop.order.requestAnotherReturn": "Request another return",
  "shop.order.requestReturn": "Request a return",
  "shop.order.chooseHowMany": "Choose how many of each item to return",
  "shop.order.returnWindowCloses": "the return window closes on",
  "shop.order.reasonOptional": "Reason (optional)",
  "shop.order.submitReturn": "Submit return request",
  "shop.order.cancel": "Cancel",
  "shop.order.selectItemReturn": "Select at least one item to return.",
  "shop.order.returnNotEligible": "This order is no longer eligible for a return.",
  "shop.order.returnSubmitError": "Couldn't submit the return. Please try again.",
};

const hr: Dict = {
  // Header / nav
  "shop.nav.shop": "Trgovina",
  "shop.nav.cart": "Košarica",
  "shop.nav.account": "Račun",
  "shop.nav.signIn": "Prijava",
  "shop.nav.orders": "Narudžbe",
  "shop.nav.wishlist": "Lista želja",

  // Generic
  "shop.loading": "Učitavanje…",
  "shop.save": "Spremi",
  "shop.cancel": "Odustani",
  "shop.edit": "Uredi",
  "shop.delete": "Obriši",
  "shop.remove": "Ukloni",
  "shop.close": "Zatvori",
  "shop.back": "Natrag",
  "shop.continue": "Nastavi",
  "shop.retry": "Pokušaj ponovno",
  "shop.optional": "neobavezno",
  "shop.somethingWrong": "Nešto je pošlo po zlu. Pokušajte ponovno.",

  // Catalog / grid
  "shop.catalog.title": "Trgovina",
  "shop.catalog.searchPlaceholder": "Pretraži proizvode…",
  "shop.catalog.clearSearch": "Očisti pretragu",
  "shop.catalog.sortLabel": "Sortiraj proizvode",
  "shop.catalog.noImage": "Nema slike",
  "shop.catalog.noMatches": "Nema proizvoda koji odgovaraju filtrima.",
  "shop.catalog.productCountOne": "proizvod",
  "shop.catalog.productCountOther": "proizvoda",
  "shop.sort.newest": "Najnovije",
  "shop.sort.priceAsc": "Cijena: niža → viša",
  "shop.sort.priceDesc": "Cijena: viša → niža",
  "shop.sort.nameAsc": "Naziv: A → Ž",
  "shop.sort.nameDesc": "Naziv: Ž → A",

  // Badges / stock
  "shop.badge.inquiryOnly": "Samo upit",
  "shop.badge.sale": "Akcija",
  "shop.badge.inStock": "Na zalihi",
  "shop.badge.backorder": "Naknadna narudžba",
  "shop.badge.backorderAvailable": "Dostupno na naknadnu narudžbu",
  "shop.badge.outOfStock": "Nema na zalihi",
  "shop.badge.verifiedPurchase": "Potvrđena kupnja",
  "shop.priceOnRequest": "Cijena na upit",

  // Facets
  "shop.facets.title": "Filtri",
  "shop.facets.clearAll": "Očisti sve",
  "shop.facets.category": "Kategorija",
  "shop.facets.allCategories": "Sve kategorije",
  "shop.facets.type": "Vrsta",
  "shop.facets.allTypes": "Sve vrste",
  "shop.facets.price": "Cijena (€)",
  "shop.facets.min": "Min",
  "shop.facets.max": "Maks",
  "shop.facets.inStockOnly": "Samo na zalihi",
  "shop.facets.categoryFallback": "Kategorija",
  "shop.type.physical": "Fizički",
  "shop.type.digital": "Digitalni",
  "shop.type.service": "Usluga",

  // Product page
  "shop.product.quantity": "Količina",
  "shop.product.addToCart": "Dodaj u košaricu",
  "shop.product.addToInquiry": "Dodaj u upit",
  "shop.product.selectOptions": "Odaberite sve opcije za cijenu i dostupnost.",
  "shop.product.priceOnRequest": "Cijena na upit",
  "shop.product.inStockCount": "Na zalihi",
  "shop.product.sku": "SKU",
  "shop.product.lowestPrice": "Najniža cijena u posljednjih 30 dana",
  "shop.product.notFound": "Proizvod nije pronađen.",

  // Wishlist button
  "shop.wishlist.add": "Dodaj u listu želja",
  "shop.wishlist.remove": "Ukloni iz liste želja",

  // Back-in-stock
  "shop.backInStock.notifyMe": "Obavijesti me kad bude na zalihi",
  "shop.backInStock.emailPlaceholder": "Vaš e-mail",
  "shop.backInStock.subscribe": "Obavijesti me",
  "shop.backInStock.done": "Javit ćemo vam e-mailom kad ovo ponovno bude na zalihi.",
  "shop.backInStock.alreadyInStock": "Ovaj artikl je ponovno na zalihi.",
  "shop.backInStock.error": "Prijava nije uspjela. Pokušajte ponovno.",

  // Reviews
  "shop.reviews.title": "Recenzije",
  "shop.reviews.none": "Još nema recenzija.",
  "shop.reviews.anonymous": "Anonimno",
  "shop.reviews.awaitingApproval": "Vaša recenzija čeka odobrenje.",
  "shop.reviews.write": "Napišite recenziju",
  "shop.reviews.titlePlaceholder": "Naslov (neobavezno)",
  "shop.reviews.bodyPlaceholder": "Podijelite svoje iskustvo (neobavezno)",
  "shop.reviews.submit": "Pošalji recenziju",
  "shop.reviews.pickRating": "Prvo odaberite ocjenu.",
  "shop.reviews.thanks": "Hvala! Vaša recenzija čeka odobrenje.",
  "shop.reviews.signInToReview": "za pisanje recenzije.",
  "shop.reviews.verifyToReview": "Potvrdite e-mail za pisanje recenzije.",
  "shop.reviews.buyersOnly": "Samo kupci koji su kupili ovaj proizvod mogu napisati recenziju.",
  "shop.reviews.exists": "Već ste recenzirali ovaj proizvod.",
  "shop.reviews.submitError": "Recenziju nije moguće poslati. Pokušajte ponovno.",

  // Wishlist button
  "shop.wishlist.save": "Spremi",
  "shop.wishlist.saved": "Spremljeno",

  // Header extras
  "shop.nav.skipToContent": "Presko\u010di na sadr\u017eaj",
  "shop.nav.cookieSettings": "Postavke kola\u010di\u0107a",

  // Catalog extras
  "shop.catalog.browse": "Pregledaj:",
  "shop.category.subcategories": "Potkategorije:",

  // Back-in-stock extras
  "shop.backInStock.title": "Obavijesti me kad ponovno bude dostupno",
  "shop.backInStock.emailExample": "vi@primjer.com",
  "shop.backInStock.confirmed": "\u2713 Javit \u0107emo vam kad ponovno bude dostupno.",
  "shop.backInStock.alreadyOnList": "Ve\u0107 ste na popisu \u2014 javit \u0107emo vam e-mailom kad bude dostupno.",
  "shop.backInStock.willEmail": "Javit \u0107emo vam e-mailom kad ponovno bude na zalihi.",
  "shop.backInStock.subscribeError": "Prijava nije uspjela. Provjerite e-mail adresu i poku\u0161ajte ponovno.",

  // Product extras
  "shop.product.backToShop": "\u2190 Natrag u trgovinu",
  "shop.product.addedToCart": "ko\u0161aricu",
  "shop.product.addedToInquiry": "upit",

  // Cookie banner
  "shop.cookie.text": "Koristimo analiti\u010dke kola\u010di\u0107e kako bismo razumjeli kori\u0161tenje trgovine. Postavljaju se samo ako prihvatite \u2014 odbijanje ne utje\u010de na rad trgovine.",
  "shop.cookie.decline": "Odbij",
  "shop.cookie.accept": "Prihvati analitiku",
  "shop.cookie.region": "Privola za kola\u010di\u0107e",

  // Cart
  "shop.cart.title": "Va\u0161a ko\u0161arica",
  "shop.cart.empty": "Va\u0161a ko\u0161arica je prazna.",
  "shop.cart.continueShopping": "\u2190 Nastavi kupovinu",
  "shop.cart.clear": "Isprazni ko\u0161aricu",
  "shop.cart.summary": "Sa\u017eetak",
  "shop.cart.businessPricing": "Poslovne cijene",
  "shop.cart.remove": "Ukloni",
  "shop.cart.removeCoupon": "Ukloni kupon",
  "shop.cart.decrease": "Smanji",
  "shop.cart.increase": "Pove\u0107aj",
  "shop.cart.max": "maks",
  "shop.cart.onRequest": "Na upit",
  "shop.cart.inquiryPriceOnRequest": "Upit \u2014 cijena na upit",
  "shop.cart.mixedInquiryNote": "Va\u0161a ko\u0161arica sadr\u017ei artikle samo za upit, pa cijela narud\u017eba postaje zahtjev za ponudu \u2014 pla\u0107anje i dostava se ovdje ne obra\u010dunavaju. Za kupnju ostalih artikala odmah, uklonite artikle samo za upit iz ko\u0161arice.",
  "shop.cart.inquiryNote": "Ovi artikli su samo za upit \u2014 pripremit \u0107emo ponudu i javiti se e-mailom. Pla\u0107anje i dostava se ovdje ne obra\u010dunavaju.",
  "shop.cart.sendInquiry": "Po\u0161alji upit",
  "shop.cart.coupon": "Kupon",
  "shop.cart.freeShipping": "Besplatna dostava",
  "shop.cart.couponsAdditive": "Svaki kupon primjenjuje se na izvorni me\u0111uzbroj (popusti se zbrajaju).",
  "shop.cart.addAnotherCoupon": "Dodaj jo\u0161 jedan kupon",
  "shop.cart.couponCode": "Kod kupona",
  "shop.cart.couponSolo": "Ovaj kupon ne mo\u017ee se kombinirati s drugima \u2014 uklonite ga da biste upotrijebili drugi kod.",
  "shop.cart.couponApplied": "Kupon primijenjen.",
  "shop.cart.couponRemoved": "Kupon uklonjen \u2014 vi\u0161e ne vrijedi za ovu ko\u0161aricu.",
  "shop.cart.err.not_purchasable": "Ovaj proizvod trenuta\u010dno nije dostupan za kupnju.",
  "shop.cart.err.out_of_stock": "Na\u017ealost, artikl je rasprodan.",
  "shop.cart.err.coupon_not_found": "Kod kupona nije prona\u0111en.",
  "shop.cart.err.coupon_not_applicable": "Kupon se ne mo\u017ee primijeniti na va\u0161u ko\u0161aricu.",
  "shop.cart.err.below_min_spend": "Va\u0161a ko\u0161arica je ispod minimalnog iznosa za ovaj kupon",
  "shop.cart.err.coupon_expired": "Ovaj kupon je istekao.",
  "shop.cart.err.coupon_not_started": "Ovaj kupon jo\u0161 nije aktivan.",
  "shop.cart.err.coupon_inactive": "Ovaj kupon vi\u0161e nije aktivan.",
  "shop.cart.err.usage_exhausted": "Ovaj kupon je dosegnuo ograni\u010denje broja upotreba.",
  "shop.cart.err.coupon_already_applied": "Ovaj kupon je ve\u0107 primijenjen.",
  "shop.cart.err.not_stackable": "Ovaj kupon ne mo\u017ee se kombinirati s drugim \u2014 upotrijebite ga samostalno.",
  "shop.cart.err.pickup_point_required": "Odaberite preuzimno mjesto za ovu metodu.",
  "shop.cart.err.shipping_method_not_found": "Ova metoda dostave vi\u0161e nije dostupna.",
  "shop.cart.err.default": "Ne\u0161to je po\u0161lo po zlu s ko\u0161aricom. Poku\u0161ajte ponovno.",
  "shop.cart.apply": "Primijeni",
  "shop.cart.shipping": "Dostava",
  "shop.cart.shipTo": "Dostava u",
  "shop.cart.pickupPoint": "Preuzimno mjesto",
  "shop.cart.pickupSuffix": " (preuzimno mjesto)",
  "shop.cart.free": "Besplatno",
  "shop.cart.use": "Koristi",
  "shop.cart.noShippingMethods": "Nema dostupnih na\u010dina dostave za ovo odredi\u0161te.",
  "shop.cart.pickup": "Preuzimanje",
  "shop.cart.subtotal": "Me\u0111uzbroj",
  "shop.cart.discount": "Popust",
  "shop.cart.cashOnDelivery": "Pouze\u0107em",
  "shop.cart.net": "Neto",
  "shop.cart.vat": "PDV",
  "shop.cart.taxBase": "osnovica",
  "shop.cart.total": "Ukupno",
  "shop.cart.vatExempt": "Cijene su oslobo\u0111ene PDV-a \u2014 trgovina nije u sustavu PDV-a.",
  "shop.cart.vatIncluded": "PDV uklju\u010den",
  "shop.cart.vatReverse": "Prijenos porezne obveze \u2014 va\u0161e poduze\u0107e samo obra\u010dunava PDV",
  "shop.cart.vatExport": "Izvoz oslobo\u0111en PDV-a \u2014 za dostavu izvan EU-a ne obra\u010dunava se PDV",
  "shop.cart.noVat": "Na ove artikle ne primjenjuje se PDV.",
  "shop.country.eu": "EU",
  "shop.country.intl": "me\u0111.",
  "shop.cart.checkout": "Nastavi na pla\u0107anje",

  // Order/payment/fulfillment/quote status labels (raw enum -> human)
  "shop.status.open": "Otvoreno",
  "shop.status.completed": "Zavr\u0161eno",
  "shop.status.cancelled": "Otkazano",
  "shop.status.pending": "Na \u010dekanju",
  "shop.status.awaiting_payment": "\u010ceka pla\u0107anje",
  "shop.status.authorized": "Autorizirano",
  "shop.status.paid": "Pla\u0107eno",
  "shop.status.partially_refunded": "Djelomi\u010dno vra\u0107eno",
  "shop.status.refunded": "Vra\u0107eno",
  "shop.status.voided": "Poni\u0161teno",
  "shop.status.draft": "Skica",
  "shop.status.unfulfilled": "Neispunjeno",
  "shop.status.preparing": "U pripremi",
  "shop.status.partially_shipped": "Djelomi\u010dno poslano",
  "shop.status.shipped": "Poslano",
  "shop.status.delivered": "Dostavljeno",
  "shop.status.returned": "Vra\u0107eno",
  "shop.status.sent": "Poslano",
  "shop.status.accepted": "Prihva\u0107eno",
  "shop.status.declined": "Odbijeno",
  "shop.status.expired": "Isteklo",

  // Orders history
  "shop.orders.title": "Moje narud\u017ebe",
  "shop.orders.signInPrompt": "za pregled povijesti narud\u017ebi.",
  "shop.orders.pleaseSignIn": "Molimo",
  "shop.orders.signIn": "prijavite se",
  "shop.orders.verifyTitle": "Potvrdite e-mail",
  "shop.orders.verifyBody": "Povijest narud\u017ebi je zna\u010dajka ra\u010duna \u2014 najprije potvrdite e-mail. Potvrdom se povezuju i ranije narud\u017ebe koje ste kao gost obavili s ovim e-mailom.",
  "shop.orders.goToAccount": "Idi na ra\u010dun",
  "shop.orders.loadFailedTitle": "U\u010ditavanje narud\u017ebi nije uspjelo",
  "shop.orders.loadFailedBody": "Do\u0161lo je do gre\u0161ke pri u\u010ditavanju povijesti narud\u017ebi.",
  "shop.orders.tryAgain": "Poku\u0161aj ponovno",
  "shop.orders.emptyBody": "Jo\u0161 niste obavili nijednu narud\u017ebu.",
  "shop.orders.startShopping": "Zapo\u010dni kupovinu",
  "shop.orders.quote": "Ponuda",
  "shop.orders.order": "Narud\u017eba",
  "shop.orders.itemOne": "artikl",
  "shop.orders.itemOther": "artikala",
  "shop.orders.backToAccount": "\u2190 Natrag na ra\u010dun",

  // Wishlist page
  "shop.wishlistPage.title": "Lista \u017eelja",
  "shop.wishlistPage.backToAccount": "\u2190 Natrag na ra\u010dun",
  "shop.wishlistPage.continueShopping": "\u2190 Nastavi kupovinu",
  "shop.wishlistPage.guestNote": "Va\u0161a lista \u017eelja spremljena je na ovom ure\u0111aju.",
  "shop.wishlistPage.guestNoteSuffix": "(i potvrdite e-mail) da je zadr\u017eite na svim ure\u0111ajima.",
  "shop.wishlistPage.empty": "Va\u0161a lista \u017eelja je prazna. Dodirnite srce na bilo kojem proizvodu da ga spremite ovdje.",
  "shop.wishlistPage.browse": "Pregledaj trgovinu",
  "shop.wishlistPage.savedOne": "spremljeni artikl",
  "shop.wishlistPage.savedOther": "spremljenih artikala",

  // Payment (Stripe)
  "shop.payment.payNow": "Plati sada",
  "shop.payment.failed": "Pla\u0107anje nije uspjelo. Poku\u0161ajte ponovno.",
  "shop.payment.testMode": "Test na\u010din \u2014 koristite karticu 4242 4242 4242 4242, bilo koji budu\u0107i datum isteka i CVC.",

  // Auth: forgot / reset / verify
  "shop.auth.resetTitle": "Poni\u0161tavanje lozinke",
  "shop.auth.checkInbox": "Provjerite po\u0161tu",
  "shop.auth.resetSentPrefix": "Ako ra\u010dun postoji za",
  "shop.auth.resetSentSuffix": "poslali smo poveznicu za poni\u0161tavanje lozinke. Poveznica istje\u010de za 1 sat.",
  "shop.auth.backToSignIn": "Natrag na prijavu",
  "shop.auth.forgotIntro": "Unesite svoj e-mail i poslat \u0107emo vam poveznicu za odabir nove lozinke.",
  "shop.auth.email": "E-mail",
  "shop.auth.sendResetLink": "Po\u0161alji poveznicu",
  "shop.auth.chooseNewPassword": "Odaberite novu lozinku",
  "shop.auth.checkingLink": "Provjera poveznice…",
  "shop.auth.linkInvalidTitle": "Poveznica neispravna ili istekla",
  "shop.auth.resetLinkInvalid": "Ova poveznica za poni\u0161tavanje lozinke je neispravna ili je istekla. Zatra\u017eite novu.",
  "shop.auth.requestNewLink": "Zatra\u017ei novu poveznicu",
  "shop.auth.settingPasswordFor": "Postavljanje nove lozinke za",
  "shop.auth.newPassword": "Nova lozinka",
  "shop.auth.atLeast8": "Najmanje 8 znakova",
  "shop.auth.confirmPassword": "Potvrdi lozinku",
  "shop.auth.passwordsDontMatch": "Lozinke se ne podudaraju",
  "shop.auth.setNewPassword": "Postavi novu lozinku",
  "shop.auth.verifyTitle": "Potvrda e-maila",
  "shop.auth.verifying": "Potvr\u0111ivanje e-maila…",
  "shop.auth.verifiedTitle": "E-mail potvr\u0111en",
  "shop.auth.verifiedBody": "Hvala! Va\u0161a e-mail adresa je potvr\u0111ena i zna\u010dajke ra\u010duna su otklju\u010dane.",
  "shop.auth.goToAccount": "Idi na moj ra\u010dun",
  "shop.auth.verifyFailedTitle": "Potvrda nije uspjela",
  "shop.auth.verifyFailedBody": "Ova poveznica za potvrdu je neispravna ili je istekla. Prijavite se i zatra\u017eite novu s va\u0161e stranice ra\u010duna.",

  // Account page
  "shop.account.myAccount": "Moj ra\u010dun",
  "shop.account.title": "Ra\u010dun",
  "shop.account.typePersonal": "osobni",
  "shop.account.typeBusiness": "poslovni",
  "shop.account.emailVerified": "E-mail potvr\u0111en:",
  "shop.account.verified": "potvr\u0111en",
  "shop.account.notVerified": "nije potvr\u0111en",
  "shop.account.businessPricing": "Poslovne cijene:",
  "shop.account.b2bActive": "aktivno",
  "shop.account.b2bNotApproved": "nije odobreno",
  "shop.account.b2bPending": "\u010deka odobrenje",
  "shop.account.b2bPendingTitle": "Poslovni ra\u010dun \u010deka odobrenje",
  "shop.account.b2bPendingBody": "Va\u0161 poslovni ra\u010dun \u010deka odobrenje. Mo\u017eete kupovati po standardnim cijenama \u2014 nakon odobrenja, dodijeljeni cjenik primjenjuje se automatski u cijeloj trgovini.",
  "shop.account.verifyTitle": "Potvrdite e-mail",
  "shop.account.verifyBodyPrefix": "Poslali smo poveznicu za potvrdu na",
  "shop.account.verifyBodySuffix": ". Potvrda otklju\u010dava zna\u010dajke ra\u010duna poput promjene lozinke \u2014 u me\u0111uvremenu mo\u017eete nastaviti kupovati i pla\u0107ati.",
  "shop.account.resendVerification": "Ponovno po\u0161alji potvrdu",
  "shop.account.changePassword": "Promjena lozinke",
  "shop.account.currentPassword": "Trenutna lozinka",
  "shop.account.newPassword": "Nova lozinka",
  "shop.account.confirmNewPassword": "Potvrdi novu lozinku",
  "shop.account.passwordsDontMatch": "Lozinke se ne podudaraju",
  "shop.account.updatePassword": "A\u017euriraj lozinku",
  "shop.account.verifyToChangePassword": "Potvrdite e-mail za promjenu lozinke.",
  "shop.account.myOrders": "Moje narud\u017ebe",
  "shop.account.addressBook": "Adresar",
  "shop.account.wishlist": "Lista \u017eelja",
  "shop.account.viewCart": "Pogledaj ko\u0161aricu",
  "shop.account.signOut": "Odjava",
  "shop.account.cartMovePrefix": "Imate",
  "shop.account.cartMoveOne": "artikl u ko\u0161arici \u2014 prijavite se ili izradite ra\u010dun i preselit \u0107e se s vama.",
  "shop.account.cartMoveOther": "artikala u ko\u0161arici \u2014 prijavite se ili izradite ra\u010dun i preselit \u0107e se s vama.",
  "shop.account.signIn": "Prijava",
  "shop.account.createAccount": "Izradi ra\u010dun",
  "shop.account.email": "E-mail",
  "shop.account.password": "Lozinka",
  "shop.account.forgotPassword": "Zaboravili ste lozinku?",
  "shop.account.personal": "Osobni",
  "shop.account.businessB2B": "Poslovni (B2B)",
  "shop.account.company": "Tvrtka",
  "shop.account.oib": "OIB",
  "shop.account.oib11": "11 znamenki",
  "shop.account.vatId": "PDV ID",
  "shop.account.vatIdExample": "npr. HR12345678901",
  "shop.account.b2bHint": "Unesite OIB (11 znamenki) ili EU PDV ID. Poslovni ra\u010duni pregledavaju se prije primjene B2B cijena \u2014 u me\u0111uvremenu mo\u017eete kupovati po standardnim cijenama.",
  "shop.account.firstName": "Ime",
  "shop.account.lastName": "Prezime",
  "shop.account.confirmPassword": "Potvrdi lozinku",
  "shop.account.atLeast8": "Najmanje 8 znakova",
  "shop.account.businessMustUseForm": "Poslovni ra\u010duni moraju se izraditi gornjim obrascem.",
  "shop.account.or": "ili",
  "shop.account.guestCheckout": "Kupnja kao gost uvijek je dostupna \u2014 ra\u010dun nije obavezan.",
  "shop.account.continueShopping": "Nastavi kupovinu",
  "shop.account.required": "Obavezno.",
  "shop.account.invalidEmail": "Unesite ispravnu e-mail adresu.",
  "shop.account.min8": "Najmanje 8 znakova.",
  "shop.account.provideTaxId": "Unesite OIB ili PDV ID.",
  "shop.account.invalidOib": "Neispravan OIB \u2014 11 znamenki s ispravnom kontrolnom znamenkom.",
  "shop.account.invalidVatId": "Unesite ispravan PDV ID.",
  "shop.oauth.google": "Nastavi s Google",
  "shop.oauth.apple": "Nastavi s Apple",
  "shop.oauth.stub": "Dev prijava (stub)",
  "shop.oauth.err.oauth_failed": "Prijava nije dovr\u0161ena. Poku\u0161ajte ponovno.",
  "shop.oauth.err.oauth_account_exists": "Ra\u010dun s ovim e-mailom ve\u0107 postoji. Prijavite se lozinkom (ili je poni\u0161tite), zatim mo\u017eete povezati ovog pru\u017eatelja.",
  "shop.oauth.err.oauth_email_unverified": "Pru\u017eatelj nije podijelio potvr\u0111eni e-mail pa vas nismo mogli prijaviti.",
  "shop.oauth.err.account_disabled": "Ovaj ra\u010dun je onemogu\u0107en.",
  "shop.oauth.linked": "Prijavljeni ste \u2014 ovaj pru\u017eatelj sada je povezan s va\u0161im ra\u010dunom.",
  "shop.oauth.signedIn": "Prijavljeni ste.",

  // Address book
  "shop.addr.title": "Adresar",
  "shop.addr.signInPrompt": "za upravljanje spremljenim adresama.",
  "shop.addr.verifyTitle": "Potvrdite e-mail",
  "shop.addr.verifyBody": "Spremanje adresa je zna\u010dajka ra\u010duna \u2014 najprije potvrdite e-mail. I dalje mo\u017eete pla\u0107ati kao gost unosom adrese pri naplati.",
  "shop.addr.goToAccount": "Idi na ra\u010dun",
  "shop.addr.add": "Dodaj adresu",
  "shop.addr.empty": "Jo\u0161 niste spremili nijednu adresu. Dodajte je i automatski \u0107e se popuniti pri naplati.",
  "shop.addr.defaultShipping": "Zadana dostava",
  "shop.addr.defaultBilling": "Zadano pla\u0107anje",
  "shop.addr.setDefaultShipping": "Postavi kao zadanu za dostavu",
  "shop.addr.setDefaultBilling": "Postavi kao zadanu za pla\u0107anje",
  "shop.addr.edit": "Uredi",
  "shop.addr.confirm": "Potvrdi",
  "shop.addr.cancel": "Odustani",
  "shop.addr.delete": "Obri\u0161i",
  "shop.addr.backToAccount": "\u2190 Natrag na ra\u010dun",
  "shop.addr.editTitle": "Uredi adresu",
  "shop.addr.addTitle": "Dodaj adresu",
  "shop.addr.label": "Oznaka (neobavezno)",
  "shop.addr.labelPlaceholder": "Ku\u0107a, Posao…",
  "shop.addr.fullName": "Puno ime",
  "shop.addr.address": "Adresa",
  "shop.addr.addressLine2": "Adresa, redak 2",
  "shop.addr.city": "Grad",
  "shop.addr.postalCode": "Po\u0161tanski broj",
  "shop.addr.country": "Dr\u017eava (ISO-2)",
  "shop.addr.phone": "Telefon",
  "shop.addr.defaultShippingCheckbox": "Zadana adresa za dostavu",
  "shop.addr.defaultBillingCheckbox": "Zadana adresa za pla\u0107anje",
  "shop.addr.saveChanges": "Spremi promjene",
  "shop.addr.updated": "Adresa a\u017eurirana.",
  "shop.addr.saved": "Adresa spremljena.",
  "shop.addr.verifyToSave": "Najprije potvrdite e-mail za spremanje adresa.",
  "shop.addr.saveError": "Adresu nije mogu\u0107e spremiti. Provjerite polja i poku\u0161ajte ponovno.",
  "shop.addr.defaultError": "Zadanu adresu nije mogu\u0107e a\u017eurirati.",
  "shop.addr.removed": "Adresa uklonjena.",
  "shop.addr.removeError": "Adresu nije mogu\u0107e ukloniti.",

  // Checkout
  "shop.checkout.title": "Naplata",
  "shop.checkout.sendInquiry": "Po\u0161alji upit",
  "shop.checkout.empty": "Va\u0161a ko\u0161arica je prazna.",
  "shop.checkout.continueShopping": "\u2190 Nastavi kupovinu",
  "shop.checkout.mixedQuotePrefix": "Va\u0161a ko\u0161arica sadr\u017ei artikle samo za upit, pa je cijela narud\u017eba",
  "shop.checkout.quoteRequest": "zahtjev za ponudu",
  "shop.checkout.mixedQuoteSuffix": "\u2014 pla\u0107anje i dostava se ne obra\u010dunavaju. Za pla\u0107anje ostalih artikala, vratite se u ko\u0161aricu i uklonite artikle samo za upit.",
  "shop.checkout.inquiryPrefix": "Ovi artikli su samo za upit pa je ovo",
  "shop.checkout.inquirySuffix": ". Pla\u0107anje se sada ne napla\u0107uje \u2014 pripremit \u0107emo ponudu i javiti se e-mailom.",
  "shop.checkout.useSavedAddress": "Koristi spremljenu adresu",
  "shop.checkout.enterNewAddress": "Unesi novu adresu",
  "shop.checkout.contact": "Kontakt",
  "shop.checkout.email": "E-mail",
  "shop.checkout.shippingAddress": "Adresa za dostavu",
  "shop.checkout.billingAddress": "Adresa za ra\u010dun",
  "shop.checkout.fullName": "Puno ime",
  "shop.checkout.address": "Adresa",
  "shop.checkout.addressLine2": "Adresa, redak 2",
  "shop.checkout.city": "Grad",
  "shop.checkout.postalCode": "Po\u0161tanski broj",
  "shop.checkout.country": "Dr\u017eava",
  "shop.checkout.phone": "Telefon",
  "shop.checkout.billingSame": "Adresa za ra\u010dun ista kao za dostavu",
  "shop.checkout.orderNote": "Napomena uz narud\u017ebu",
  "shop.checkout.marketingOptIn": "\u017delim primati ponude i novosti e-mailom",
  "shop.checkout.marketingHint": "Neobavezno \u2014 mo\u017eete se odjaviti bilo kada.",
  "shop.checkout.backToCart": "\u2190 Natrag u ko\u0161aricu",
  "shop.checkout.orderSummary": "Sa\u017eetak narud\u017ebe",
  "shop.checkout.onRequest": "Na upit",
  "shop.checkout.noQuoteTotal": "Za ponudu se ne obra\u010dunava ukupni iznos \u2014 poslat \u0107emo vam ponudu s cijenama.",
  "shop.checkout.subtotal": "Me\u0111uzbroj",
  "shop.checkout.discount": "Popust",
  "shop.checkout.free": "Besplatno",
  "shop.checkout.cashOnDelivery": "Pouze\u0107em",
  "shop.checkout.net": "Neto",
  "shop.checkout.vat": "PDV",
  "shop.checkout.estimatedTotal": "Procijenjeni ukupni iznos",
  "shop.checkout.total": "Ukupno",
  "shop.checkout.vatExempt": "Cijene su oslobo\u0111ene PDV-a \u2014 trgovina nije u sustavu PDV-a.",
  "shop.checkout.vatShownFor": "PDV prikazan za",
  "shop.checkout.noVat": "Na ove artikle ne primjenjuje se PDV.",
  "shop.checkout.paymentMethod": "Na\u010din pla\u0107anja",
  "shop.checkout.noPayableMethod": "Za ovu ko\u0161aricu nije dostupan nijedan na\u010din pla\u0107anja \u2014 va\u0161 artikl zahtijeva pla\u0107anje pouze\u0107em, ali odabrani na\u010din dostave to ne podr\u017eava. Odaberite dostavu kurirom na stranici ko\u0161arice.",
  "shop.checkout.chooseDelivery": "Odaberite na\u010din dostave za nastavak.",
  "shop.checkout.selectOnCart": "Odaberite ga na stranici ko\u0161arice",
  "shop.checkout.placeOrder": "Naru\u010di",
  "shop.checkout.fillToContinue": "Unesite e-mail i adresu za dostavu za nastavak.",
  "shop.checkout.enterValidEmail": "Unesite ispravnu e-mail adresu.",
  "shop.checkout.fullNameRequired": "Puno ime je obavezno.",
  "shop.checkout.addressRequired": "Adresa je obavezna.",
  "shop.checkout.cityRequired": "Grad je obavezan.",
  "shop.checkout.postalRequired": "Po\u0161tanski broj je obavezan.",
  "shop.checkout.emailPlaceholder": "vi@primjer.com",
  "shop.pay.pay_now": "Plati sada (kartica)",
  "shop.pay.pay_now.help": "Platite sigurno karticom u sljede\u0107em koraku.",
  "shop.pay.bank_transfer": "Bankovni prijenos",
  "shop.pay.bank_transfer.help": "Poslat \u0107emo upute za pla\u0107anje e-mailom; narud\u017eba se \u0161alje nakon primitka uplate.",
  "shop.pay.cod": "Pouze\u0107em",
  "shop.pay.cod.help": "Platite gotovinom pri dostavi narud\u017ebe (uz doplatu).",
  "shop.checkout.err.cart_empty": "Va\u0161a ko\u0161arica je prazna.",
  "shop.checkout.err.insufficient_stock": "Na\u017ealost \u2014 jedan od va\u0161ih artikala upravo je rasprodan.",
  "shop.checkout.err.coupon_exhausted": "Va\u0161 kupon je upravo iskori\u0161ten. Uklonite ga i poku\u0161ajte ponovno.",
  "shop.checkout.err.payment_method_unavailable": "Taj na\u010din pla\u0107anja nije dostupan za ovu ko\u0161aricu. Odaberite drugu opciju.",
  "shop.checkout.err.default": "Naplata nije uspjela. Poku\u0161ajte ponovno.",

  // Status labels for returns
  "shop.status.requested": "Zatra\u017eeno",
  "shop.status.approved": "Odobreno",
  "shop.status.rejected": "Odbijeno",

  // Order page
  "shop.order.notFound": "Narud\u017eba nije prona\u0111ena",
  "shop.order.notFoundBody": "Tu narud\u017ebu nismo mogli prona\u0107i.",
  "shop.order.continueShopping": "\u2190 Nastavi kupovinu",
  "shop.order.quoteReceivedPrefix": "Va\u0161",
  "shop.order.quoteRequest": "zahtjev za ponudu",
  "shop.order.quoteReceivedMid": "je zaprimljen. Poslat \u0107emo ponudu e-mailom na",
  "shop.order.authorizedPrefix": "Va\u0161a kartica je",
  "shop.order.authorized": "autorizirana",
  "shop.order.authorizedMid": "za narud\u017ebu",
  "shop.order.authorizedSuffix": "\u2014 ne\u0107ete biti tere\u0107eni dok se ne po\u0161alje. Potvrda \u0107e biti poslana na",
  "shop.order.paidPrefix": "Uplata zaprimljena \u2014 hvala! Narud\u017eba",
  "shop.order.paidMid": "je potvr\u0111ena. Ra\u010dun \u0107e biti poslan na",
  "shop.order.placedPrefix": "Hvala! Narud\u017eba",
  "shop.order.placedMid": "je zaprimljena i \u010deka pla\u0107anje. Potvrda \u0107e biti poslana na",
  "shop.order.orderNo": "Narud\u017eba",
  "shop.order.invoicePdf": "Ra\u010dun (PDF)",
  "shop.order.yourDownloads": "Va\u0161a preuzimanja",
  "shop.order.linkExpired": "Poveznica istekla",
  "shop.order.download": "Preuzmi",
  "shop.order.linkValidUntil": "Poveznica vrijedi do",
  "shop.order.licenseKey": "Licencni klju\u010d",
  "shop.order.licenseKeys": "Licencni klju\u010devi",
  "shop.order.fulfill.preparing": "Va\u0161a narud\u017eba se priprema za otpremu.",
  "shop.order.fulfill.partially_shipped": "Dio va\u0161e narud\u017ebe je na putu \u2014 ostatak slijedi.",
  "shop.order.fulfill.shipped": "Va\u0161a narud\u017eba je poslana i na putu je.",
  "shop.order.fulfill.delivered": "Va\u0161a narud\u017eba je dostavljena. U\u017eivajte!",
  "shop.order.fulfill.returned": "Ova narud\u017eba je vra\u0107ena.",
  "shop.order.quoteReadyTitle": "Va\u0161a ponuda je spremna",
  "shop.order.quoteReviewPrefix": "Pregledajte artikle i ukupni iznos u nastavku",
  "shop.order.quoteValidUntil": "vrijedi do",
  "shop.order.quoteReviewSuffix": "Prihvatite za potvrdu i nastavak na pla\u0107anje ili odbijte ako vam vi\u0161e ne odgovara.",
  "shop.order.acceptQuote": "Prihvati ponudu",
  "shop.order.decline": "Odbij",
  "shop.order.acceptError.stock": "Neki artikli vi\u0161e nisu na zalihi \u2014 javit \u0107emo vam se.",
  "shop.order.acceptError.generic": "Ponudu nije mogu\u0107e prihvatiti. Poku\u0161ajte ponovno.",
  "shop.order.declineError": "Ponudu nije mogu\u0107e odbiti. Poku\u0161ajte ponovno.",
  "shop.order.declinedNote": "Odbili ste ovu ponudu.",
  "shop.order.payment": "Pla\u0107anje",
  "shop.order.bankTransferPrefix": "Platite",
  "shop.order.bankTransfer": "bankovnim prijenosom",
  "shop.order.bankTransferMid": "koriste\u0107i podatke s predra\u010duna u nastavku",
  "shop.order.by": "do",
  "shop.order.bankReserved": "Va\u0161a narud\u017eba je rezervirana i \u0161alje se nakon primitka uplate.",
  "shop.order.downloadProforma": "Preuzmi predra\u010dun (PDF)",
  "shop.order.codPrefix": "",
  "shop.order.codPayInCash": "platit \u0107ete gotovinom pri dostavi",
  "shop.order.codSurchargePrefix": "(uklju\u010duju\u0107i",
  "shop.order.codSurchargeSuffix": "doplate za pouze\u0107e)",
  "shop.order.codNoPaymentNow": ". Pla\u0107anje sada nije potrebno.",
  "shop.order.confirmingPayment": "Potvr\u0111ivanje pla\u0107anja…",
  "shop.order.holdNotice": "Sada \u0107emo samo rezervirati iznos na va\u0161oj kartici \u2014 tere\u0107eni ste kad se narud\u017eba po\u0161alje.",
  "shop.order.authorizeIntro": "Autorizirajte karticu za potvrdu narud\u017ebe \u2014 tere\u0107eni ste tek kad se po\u0161alje.",
  "shop.order.payIntro": "Platite sigurno karticom za potvrdu narud\u017ebe.",
  "shop.order.authorizeCard": "Autoriziraj karticu",
  "shop.order.payByCard": "Plati karticom",
  "shop.order.payStartError": "Pla\u0107anje nije mogu\u0107e zapo\u010deti. Poku\u0161ajte ponovno.",
  "shop.order.followUpEmail": "Javit \u0107emo vam se e-mailom s uputama za pla\u0107anje.",
  "shop.order.items": "Artikli",
  "shop.order.shipped": "Poslano",
  "shop.order.shippedOf": "Poslano {n} od {total}",
  "shop.order.shipsSoon": "Uskoro se \u0161alje",
  "shop.order.subtotal": "Me\u0111uzbroj",
  "shop.order.discount": "Popust",
  "shop.order.cashOnDelivery": "Pouze\u0107em",
  "shop.order.net": "Neto",
  "shop.order.vat": "PDV",
  "shop.order.estimatedTotal": "Procijenjeni ukupni iznos",
  "shop.order.total": "Ukupno",
  "shop.order.noVatCharged": "Na ovu narud\u017ebu nije napla\u0107en PDV.",
  "shop.order.shippingTo": "Dostava na",
  "shop.order.method": "Na\u010din",
  "shop.order.pickupPoint": "preuzimno mjesto",
  "shop.order.billing": "Ra\u010dun",
  "shop.order.returns": "Povrati",
  "shop.order.returnsEmailPrefix": "Za zahtjev za povrat, po\u0161aljite nam e-mail na",
  "shop.order.requestAnotherReturn": "Zatra\u017ei jo\u0161 jedan povrat",
  "shop.order.requestReturn": "Zatra\u017ei povrat",
  "shop.order.chooseHowMany": "Odaberite koliko \u017eelite vratiti za svaki artikl",
  "shop.order.returnWindowCloses": "rok za povrat zatvara se",
  "shop.order.reasonOptional": "Razlog (neobavezno)",
  "shop.order.submitReturn": "Po\u0161alji zahtjev za povrat",
  "shop.order.cancel": "Odustani",
  "shop.order.selectItemReturn": "Odaberite barem jedan artikl za povrat.",
  "shop.order.returnNotEligible": "Ova narud\u017eba vi\u0161e nije prihvatljiva za povrat.",
  "shop.order.returnSubmitError": "Zahtjev za povrat nije mogu\u0107e poslati. Poku\u0161ajte ponovno.",
};

export const SHOP_STRINGS: Record<string, Dict> = { en, hr };

/** Look up a bundled shop-chrome string for `locale`, falling back to EN. */
export function bundledShopString(locale: string, key: string): string | undefined {
  return SHOP_STRINGS[locale]?.[key] ?? SHOP_STRINGS[SHOP_FALLBACK_LOCALE]?.[key];
}

/**
 * Humanize a raw status enum (e.g. "awaiting_payment") for `locale`: bundled
 * label -> EN label -> a `_`->space, capitalized fallback so an unmapped value is
 * still readable rather than raw snake_case.
 */
export function humanizeStatus(locale: string, value: string): string {
  const key = "shop.status." + value;
  return (
    SHOP_STRINGS[locale]?.[key] ??
    SHOP_STRINGS[SHOP_FALLBACK_LOCALE]?.[key] ??
    value.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase())
  );
}
